export const FORM_SPEC_PLUGIN_MAX_SOCKET_PAYLOAD_BYTES = 256 * 1024;
export const FORM_SPEC_PLUGIN_SOCKET_IDLE_TIMEOUT_MS = 30_000;
export const FORM_SPEC_PLUGIN_DEFAULT_PERFORMANCE_LOG_THRESHOLD_MS = 50;
export const FORM_SPEC_PLUGIN_DEFAULT_SNAPSHOT_DEBOUNCE_MS = 250;

export const FORM_SPEC_PLUGIN_PERFORMANCE_EVENT = {
  handleQuery: "plugin.handleQuery",
} as const;
