/**
 * `@formspec/core` - Core type definitions for FormSpec
 *
 * @packageDocumentation
 */

// Re-export all types
export type {
  Validity,
  FieldState,
  FormState,
  DataSourceRegistry,
  DataSourceOption,
  FetchOptionsResponse,
  DataSourceValueType,
  MetadataSource,
  MetadataDeclarationKind,
  MetadataAuthoringSurface,
  MetadataInferenceContext,
  MetadataInferenceFn,
  MetadataSlotInferenceContext,
  MetadataSlotInferenceFn,
  MetadataPluralizationContext,
  MetadataPluralizationFn,
  ResolvedScalarMetadata,
  ResolvedMetadata,
  MetadataSourceSpan,
  ExplicitMetadataSourceForm,
  ExplicitMetadataSource,
  MetadataSlotId,
  MetadataQualifierRegistration,
  MetadataSlotRegistration,
  MetadataResolvedEntry,
  MetadataApplicableSlot,
  MetadataAnalysisResult,
  MetadataResolutionMode,
  MetadataPluralizationDisabledPolicyInput,
  MetadataPluralizationRequireExplicitPolicyInput,
  MetadataPluralizationInferIfMissingPolicyInput,
  MetadataPluralizationPolicyInput,
  MetadataValueDisabledPolicyInput,
  MetadataValueRequireExplicitPolicyInput,
  MetadataValueInferIfMissingPolicyInput,
  MetadataValuePolicyInput,
  DeclarationMetadataPolicyInput,
  MetadataPolicyInput,
  NormalizedMetadataPluralizationPolicy,
  NormalizedMetadataValuePolicy,
  NormalizedDeclarationMetadataPolicy,
  NormalizedMetadataPolicy,
  TextField,
  NumberField,
  BooleanField,
  EnumOption,
  EnumOptionValue,
  StaticEnumField,
  DynamicEnumField,
  DynamicSchemaField,
  ArrayField,
  ObjectField,
  AnyField,
  Group,
  Conditional,
  FormElement,
  FormSpec,
  EqualsPredicate,
  Predicate,
  BuiltinConstraintName,
  JsonValue,
  Provenance,
  PathTarget,
  TypeNode,
  PrimitiveTypeNode,
  EnumMember,
  EnumTypeNode,
  ArrayTypeNode,
  ObjectProperty,
  ObjectTypeNode,
  RecordTypeNode,
  UnionTypeNode,
  ReferenceTypeNode,
  DynamicTypeNode,
  CustomTypeNode,
  ConstraintNode,
  NumericConstraintNode,
  LengthConstraintNode,
  PatternConstraintNode,
  ArrayCardinalityConstraintNode,
  EnumMemberConstraintNode,
  ConstConstraintNode,
  CustomConstraintNode,
  AnnotationNode,
  DisplayNameAnnotationNode,
  DescriptionAnnotationNode,
  RemarksAnnotationNode,
  FormatAnnotationNode,
  PlaceholderAnnotationNode,
  DefaultValueAnnotationNode,
  DeprecatedAnnotationNode,
  FormatHintAnnotationNode,
  CustomAnnotationNode,
  FieldNode,
  LayoutNode,
  GroupLayoutNode,
  ConditionalLayoutNode,
  FormIRElement,
  TypeDefinition,
  FormIR,
} from "./types/index.js";

// Re-export functions and constants
export { createInitialFieldState, IR_VERSION } from "./types/index.js";

// Extension API
export type {
  ExtensionPayloadValue,
  ExtensionTypeKind,
  ExtensionApplicableType,
  ExtensionDefinition,
  CustomTypeRegistration,
  CustomConstraintRegistration,
  ConstraintTagRegistration,
  BuiltinConstraintBroadeningRegistration,
  ConstraintSemanticRole,
  CustomAnnotationRegistration,
  VocabularyKeywordRegistration,
} from "./extensions/index.js";

export {
  defineExtension,
  defineCustomType,
  defineConstraint,
  defineConstraintTag,
  defineMetadataSlot,
  defineAnnotation,
} from "./extensions/index.js";

// Re-export type guards
export {
  isField,
  isTextField,
  isNumberField,
  isBooleanField,
  isStaticEnumField,
  isDynamicEnumField,
  isDynamicSchemaField,
  isArrayField,
  isObjectField,
  isGroup,
  isConditional,
} from "./guards.js";
