/**
 * `@formspec/validator` — JSON Schema validator for FormSpec
 *
 * Backed by {@link https://github.com/cfworker/cfworker/tree/main/packages/json-schema | @cfworker/json-schema},
 * this package validates data against FormSpec-generated JSON Schemas in any
 * JavaScript runtime — including secure environments that disallow `new Function()`
 * (e.g., Cloudflare Workers).
 *
 * Unlike Ajv, `@cfworker/json-schema` silently ignores unknown keywords, so
 * FormSpec's `x-formspec-*` extension keywords require no vocabulary registration.
 *
 * @example
 * ```typescript
 * import { createFormSpecValidator } from "@formspec/validator";
 *
 * const validator = createFormSpecValidator({
 *   type: "object",
 *   required: ["name"],
 *   properties: {
 *     name: { type: "string" },
 *     country: { type: "string", "x-formspec-source": "countries" },
 *   },
 * });
 *
 * const result = validator.validate({ name: "Alice", country: "US" });
 * // result.valid === true
 * ```
 *
 * @packageDocumentation
 */

import { Validator } from "@cfworker/json-schema";
import type { OutputUnit, Schema, SchemaDraft, ValidationResult } from "@cfworker/json-schema";

export { Validator };
export type { OutputUnit, SchemaDraft, ValidationResult };

/**
 * Options for `createFormSpecValidator`.
 *
 * @public
 */
export interface CreateValidatorOptions {
  /**
   * The JSON Schema draft version to validate against.
   *
   * FormSpec generates schemas targeting JSON Schema 2020-12.
   *
   * @defaultValue `"2020-12"`
   */
  draft?: SchemaDraft;

  /**
   * When `true`, validation stops after the first error.
   * When `false`, all errors are collected.
   *
   * @defaultValue `true`
   */
  shortCircuit?: boolean;
}

/**
 * Creates a `Validator` configured for FormSpec-generated JSON Schemas.
 *
 * The returned `Validator` uses JSON Schema draft 2020-12 by default and
 * silently ignores `x-formspec-*` extension keywords — no vocabulary
 * registration is needed.
 *
 * @param schema - A JSON Schema object (typically generated by `@formspec/build`).
 * @param options - Optional configuration for draft version and error collection behavior.
 * @returns A `Validator` instance whose `validate()` method returns a `ValidationResult`.
 *
 * @public
 */
export function createFormSpecValidator(
  schema: Record<string, unknown>,
  options?: CreateValidatorOptions,
): Validator {
  const draft = options?.draft ?? "2020-12";
  const shortCircuit = options?.shortCircuit ?? true;
  // Safe cast: Schema has `[key: string]: any`, so every Record<string, unknown>
  // structurally satisfies it. We keep the public parameter as Record<string, unknown>
  // to avoid coupling consumers to @cfworker/json-schema's Schema type.
  return new Validator(schema as Schema, draft, shortCircuit);
}
